USE ROLE ACCOUNTADMIN;

-- 1) Warehouse = la "computadora" que ejecuta las consultas
CREATE WAREHOUSE IF NOT EXISTS NYC_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

-- 2) Base de datos y un schema por capa
CREATE DATABASE IF NOT EXISTS NYC_TAXI;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI.BRONZE;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI.SILVER;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI.GOLD;

-- 3) Rol con permisos solo sobre este proyecto
CREATE ROLE IF NOT EXISTS NYC_ROLE;
GRANT USAGE ON WAREHOUSE NYC_WH TO ROLE NYC_ROLE;
GRANT ALL ON DATABASE NYC_TAXI TO ROLE NYC_ROLE;
GRANT ALL ON ALL SCHEMAS IN DATABASE NYC_TAXI TO ROLE NYC_ROLE;
GRANT ROLE NYC_ROLE TO ROLE SYSADMIN;

-- 4) Usuario que usarán Kestra y dbt
CREATE USER IF NOT EXISTS NYC_SVC
  TYPE = LEGACY_SERVICE
  PASSWORD = '<TU_PASSWORD>'
  DEFAULT_ROLE = NYC_ROLE
  DEFAULT_WAREHOUSE = NYC_WH
  MUST_CHANGE_PASSWORD = FALSE;
GRANT ROLE NYC_ROLE TO USER NYC_SVC;
